### ISSUE TITLE
[UXR] Top Nav Preference test  - Step 3:  Recruit participants

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1460]
### Context:
We are conducting an evaluative research study to improve the information architecture of IdeaSpace and enhance the findability of our platform for our target audience. The business goal is to increase user awareness, findability and retention.

**Scope of this task**: 
In this task we are **recruiting the participants**. 

-------------------------------------------------

### Acceptance criteria:
- The study has been posted via different channels such as social media and VolunteerMatch
- A minimum of 20 participants have been recruited.

**Comment by katehirschman** [comment]
Hi @JulieMass ! Sending an update here as today will be my last meeting for awhile. I wanted everything all in one place so we can continue to discuss during my break. [HERE](https://docs.google.com/document/d/14FSGICSZok94NuWsm-g6EjOyqPoOmzvxXviHewfV4lw/edit) is a link to find all the necessary documentation referenced below. 
1. When you have a chance, please check out the draft of the social media post. I'd love your input and any suggestions that would make this post more like the one you did for the usability test :) 
2. I also have a draft for emails to send to participants from the usability test
3. I set the draft of our recruitment through Hotjar to pop up on IdeaSpace's landing page, but having second thoughts about this - would it be okay to have it pop up on the main page? 
4. I'm thinking about removing the first question on the survey and instead using the 3rd question since it already asks the same thing but gets us more information. What are your thoughts?
Once I get your feedback and make any needed changes, I will post the survey.
Thank you!

**Comment by JulieMass** [comment]
Hey @katehirschman ,

Thanks for sharing this document, it looks really neat and organized 👏!

1. **Canva pot design**: Hey, I really like this post! You did a great job using the Canva app! Thanks for making it open for Marilia and me to collaborate on it. That's super helpful. I've created a second option with some suggestions and I left you a comment on Canva. Let me know what you think and I hope it helps!
2. **Draft email**: I love it! I think it's perfect!
3. **Hotjar popup**: I checked it out and I love it! I also checked out our whole website to see if other teams had pop ups live to avoid overloading our audience with pop ups, but no other team seems to be having pop ups, so we are good to go with it! Feel free to launch it when you think it's ready.
4. **Survey questions:** I wasn't able to access the survey link. Can you please add me with my devlaunchers email if possible?

Great job Kate! I'm really excited to see the results of this study 😀.

**Comment by katehirschman** [comment]
Hi @JulieMass ,

Thank you, as always for your feedback! I love the additions you made to the social media post. It really needed your designer eye :)

About the Hotjar pop-up, I think my question was a little unclear. I was wondering if we could post it to the dev launchers landing page instead of IdeaSpace's landing page. Fine either way, but wanted to see to hear your thoughts.

I (hopefully) fixed the survey link in the doc, and also adding [HERE](https://www.surveymonkey.com/r/Preview/?sm=urIt_2FFGfSlNYZ3n2aL8ayaRryFUblV1C8P46xtNf3LKVY6WaQyc1LdhrGKs9IskL) for convenience.

**Comment by JulieMass** [comment]
Hey @katehirschman, can we keep this ticket for the next sprints until you return in January? Let me know, please!

**Comment by katehirschman** [comment]
Hi @JulieMass 
Have you had a chance to check out the final survey? Hopefully you can access it from the link above, let me know if not and I will take a screenshot.
Once I get the okay, I can set up the survey, hotjar, post to social media and send out the emails.
We can keep this ticket open until all the participants are recruited, unless you think we should close it and start another?
Thanks!
Kate

**Comment by JulieMass** [comment]
Hey @katehirschman ,

Thanks for giving me the heads up on this question. I totally agree with you about removing the 3rd question, "Is there anything else you'd like to share regarding the top navigation label or the website in general?" 

But I was thinking, what if they want to add a separate label that doesn't show up in the first question? Should we let them do that?

Let me know what you think!

**Comment by JulieMass** [comment]
Oh, I see. It makes more sense now LOL yes, let's keep this question then 😂.

**Comment by katehirschman** [comment]
Hi Julie, 
I've updated the Action Items doc with all information
The survey is live and I have reached out via email to several participants from the UTS
I posted on my personal LinkedIn and will reach out to Chung soon about posting on DL social media.
Here is the link to set up the hotjar once we get the okay: [https://hotjar.com/l/nReQlj
]

**Comment by katehirschman** [comment]
Hi @JulieMass 
I wanted to email some of the prior participants that were okay with being contacted again. I'm thinking participants from your usability test from 2022 would be the most appropriate. Can you take a look at the [Participant Panel](https://docs.google.com/spreadsheets/d/1EJFhzuozFpWI6nUe294voL9V6A-ZG_Du1tZjFE39htU/edit#gid=603849503
) and let me know if there's anyone who I shouldn't reach out to?

**Comment by JulieMass** [comment]
Hi @katehirschman I replied via email to keep the participant's personal info confidential.
