### ISSUE TITLE
[BUG] Dropdown Styles Broken in Idea Submission Form

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1623]
### Steps to replicate are
1. Go to IdeaSpace > Submit and idea https://devlaunchers.org/ideaspace/submit 
2. Scroll down the form and check the dropdown select under the label “What level of involvement do you want to have after submission?”

### Device and OS
- Mobile (tablets & smartphones)
- Browsers: Based on our [Google analytics analysis](https://docs.google.com/spreadsheets/d/1upYP1mvHkU3sRBg4gCeGG4P63tO5-whn6VKLMlr6qYI/edit?usp=sharing ) we should support the following browsers, Chrome, Microsoft Edge, Safari, Firefox and Opera.

### Expected behavior
Dropdown styles should adhere to both our global style guide and IdeaSpace’s UX design mockups.
<img width="1357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzdPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dc10d7c4a34648f7038002700642477dfadb52b/image.png" alt="image.png" />

### Actual behavior 
Dropdown styles deviate from our design system guidelines. For instance, the background is white instead of black.
<img width="1357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--454c1b623855ea784fbafacfb759876269c45e5c/image.png" alt="image.png" />

**Comment by JulieMass** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1623?planning-poker) with Zenhub @JulieMass

**Comment by dbradham** [comment]
QA TESTING: The styling issue looks to be fixed, but the dropdown does not close when I make a selection, and my selection is not displayed when I click outside the dropdown to close it.

@Rutuja177 can you look into this whenever you are able? Thanks!

<img width="1197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e6cf33c751b13fe4139903f6f3744750a2ac1d4/image.png" alt="image.png" />


<img width="1077" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cc3f6f5d2abb5173cd6d9946e9147aa49d630d6/image.png" alt="image.png" />


CC: @JulieMass

**Comment by dbradham** [comment]
@Rutuja177 I'm not able to submit an idea because of the involveLevel value being posted to the backend here:

<img width="1919" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--341681200c1977594461d7446a281c215941d735/image.png" alt="image.png" />

<img width="1904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f688cbdcd8263f59bef68fb27bd67a948b10bd3/image.png" alt="image.png" />

**Comment by Rutuja177** [comment]
Hey @dbradham,

<img width="1197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3FyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66d0c232648676d92f4d14b7d134c887941673be/image.png" alt="image.png" />

Regarding the first issue, the Dropdown component sourced from the Style guide doesn't automatically close after a selection or update the title with the chosen option. 

We need to update the existing dropdown component to include this functionality. 

Let me know your thoughts on this.

@JulieMass

**Comment by dbradham** [comment]
<img width="1915" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnRLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62fe5fa8f182c6482e6ab6557e780b5d4567ee70/image.png" alt="image.png" />

I was able to find the `receiveValue` callback within the `Dropdown` component is the problem with the initial value not being set.

<img width="1885" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnhLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bca3bf6c504cd5a89b1f17cc15705154c388be8b/image.png" alt="image.png" />

**Comment by dbradham** [comment]
https://github.com/dev-launchers/dev-launchers-platform/pull/1812

**Comment by dbradham** [comment]
<img width="1254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2RLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd686c8cff573c8060ee01ed956201121bf8d32a/image.png" alt="image.png" />

**Comment by dbradham** [comment]
@JulieMass @chadcrotchett this has passed my QA testing. I have a pull request to get this bug fix, for the dropdown values not being set on the initial click, deployed to production-https://github.com/dev-launchers/dev-launchers-platform/pull/1828

**Comment by JulieMass** [comment]
> @JulieMass @chadcrotchett this has passed my QA testing. I have a pull request to get this bug fix, for the dropdown values not being set on the initial click, deployed to production-#1828

(CC. @chadcrotchett )

Hi @dbradham  and @Rutuja177 ,

I noticed an issue with the radio buttons inside the dropdown menu. They appear compressed and I'm also unable to select the third option: "I want to 'own' this idea to help with workshopping and designing until it becomes a project." 

Could you both please take a look at this?

![image](https://github.com/dev-launchers/dev-launchers-platform/assets/104226366/b0d4e59a-166e-45f7-8537-c554f767e5c3)

**Comment by Enjoy2Live** [comment]
@dbradham @JulieMass This is probably the first time I'm seeing this issue, if there's anything that is blocking you guys regarding implementation of shared components feel free to @me here on gh issues.

The dropdown in use (currently in prod) is considered deprecated thus it doesn't adhere to our global style guide and any changes on the figma components won't be reflected on the one being used by ideaspace's team so I suggest switching to the new maintained drowdown component found in [here](https://master--632ca21aeea1618b7fa0bf48.chromatic.com/?path=/docs/components-dropdownmenu--docs).

also I really like the suggestion of @Rutuja177 regarding closing the dropdown after selection, can you please create an issue with label "Platform Enablement" describing current behavior and expected one?

**Comment by zar92** [comment]
Please confirm whether this problem is solved now. @dbradham @JulieMass CC: @chungthuang

**Comment by chadcrotchett** [comment]
@dbradham do you get comments if I add them from ZenHub?

I see Prod and Staging both work the same now, which means the drop-down does not close on either. What are our options for either fixing, redesigning, or otherwise solving this dropdown issue so that it performs as a standard dropdown, which would include:

1. Close dropdown after clicked
2. Display selected option in Dropdown text after selected

Possible solutions:
1. Disable over-complicated dropdown styling
2. Update to new dropdown that is now standard per Mohammed
3. Disable dropdown as a whole (and make sure it's not a required field)

**Comment by dbradham** [comment]
@chadcrotchett yes I get the notifications. My preference is solution #1.

**Comment by Enjoy2Live** [comment]
@dbradham I highly recommend switching to the new dropdown component

**Comment by dbradham** [comment]
@Enjoy2Live I'm not sure what exactly the new dropdown component is. Are you referring to the "DropdownMenu.tsx" in the packages library, or something else?

It doesn't look like the "DropdownMenu.tsx" has been implemented yet. Given the lack of TypeScript experience on our team, I'd prefer that we are not the first team to implement it.

**Comment by dbradham** [comment]
@Enjoy2Live I am looking at the references in the project (see image below) and do not see it has been implemented on the website yet. (on branch `master`)

When we implemented the old dropdown menu, it gave us issues when it started acting unexpectedly. I do not want us to be the first team to implement components, because then we will need to debug the TypeScript if they are acting unexpectedly. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2o4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3918fb685fe3b5b280f91ac3c420620254af65a/Screenshot%202024-07-22%20at%207.07.30%20PM.png" alt="Screenshot 2024-07-22 at 7.07.30 PM.png" />

**Comment by Enjoy2Live** [comment]
@dbradham 
it's already implemented in storybook, see `packages/UI/src/components/DropdownMenu/DropdownMenu.stories.tsx`. we have made 4 examples for you to pick from.

> When we implemented the old dropdown menu, it gave us issues when it started acting unexpectedly. I do not want us to be the first team to implement components.

I understand but I hope this is not also the same approach other teams follow because no one seems to be interested in using these new components.

>  because then we will need to debug the TypeScript if they are acting unexpectedly.

Typescript is a superset of javascript meaning valid javascript code is also a valid typescript code, if something wrong happens in the component you can write regular javascript to fix it and debug it.
