### ISSUE TITLE
[Dev](User Profile) Edit Profile Picture Button functionality

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#919]
As a dev launchers user
I want to update my profile picture
So that my picture is more professional.

Given I am on the Photo tab of the Edit Profile modale
When I click “Change”
Then the Upload Photo Screen appears in the Edit modal (more below)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzUrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46829be8782e095df0ccf094b02069414dd86462/Edit%20Photo.png)

**Comment by awaswick** [comment]
As Nacy Newbie
I want to update my profile picture 
So that my picture is more professional. 


Given I am on the Photo tab of the Edit Profile modal
When I click “Change”
Then the Upload Photo Screen appears in the Edit modal

Given I am on the Upload Photo Screen
When I click “Choose Files”
Then I can select a file.jpg to upload from my PC to my user profile 
(what are the size and file type requirements?) 

OR

Given I am on the Upload Photo Screen
When I drag and drop a file.jpg into the dotted line square
Then the dropped file.jpg is uploaded to my user profile
(what are the size and file type requirements?) 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3grQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a20e0f59aa3203f740f9fa6225da6304d17991f0/Edit%20Photo.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzErQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da629307ed1d0f9e6c8e3a19b444af85c899acfd/Edit%20Photo_upload_photo.png)
