### ISSUE TITLE
[Dev](User Profile) PositionCard shared component in Opportunities section Sizing Fix

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#989]
**Describe the bug**
Opportunities card needs resizing/styling update
**Current styling:** 
![Screenshot 2023-04-02 at 15.43.35.png](https://images.zenhubusercontent.com/6404cfc245aeb948e3148743/7ae6e112-b636-4b3c-8db5-3b6222c1237b)

**Screenshots**

**Comment by judeamos** [comment]
@ethanzlevin Which styling should be applied, based on whats available here: https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=organisms-positioncard--long-a-save-only-closed&buildNumber=225&k=640369f6738e94f26b5eb76e-1200-interactive-true&h=46&b=-35

**Comment by rinagobo** [comment]
I thought "Long B Save Only Closed" or "Long B All H Closed" are the better option here because their appearances are clear. What do you think and which one should I choose![Screenshot 2023-04-21 at 2.20.18 AM.png](https://images.zenhubusercontent.com/64207ad43bdbe192c736be9a/e806acf4-0ece-459f-af91-d8f739f60c38)![Screenshot 2023-04-21 at 2.20.09 AM.png](https://images.zenhubusercontent.com/64207ad43bdbe192c736be9a/bcff5e1a-87ea-4b92-a3cc-3ea6ab8ba735)?

**Comment by rinagobo** [comment]
When I accessed "http://localhost:3000/projects/opportunities" the page was all white. Am I looking the correct page for this task![Screenshot 2023-04-21 at 2.39.26 AM.png](https://images.zenhubusercontent.com/64207ad43bdbe192c736be9a/64d18d2a-c2a9-46e4-808c-eeead3156acb)?

**Comment by ethanzlevin** [comment]
@rinagobo Long B Save Only Closed

**Comment by rinagobo** [comment]
I found out 2 things and tried to fix them on my branch.

1. Opportunities.js  >  <PositionCard>  > buttonStyle = "a" 
I changed "a" to "b".

→　"MORE DETAILS" and "APPLY" buttons are still not shown.

2. Inspect from google development tool: 
<div class="StyledPositionCard_Header..."> doesn't fit in the parent div <div class="StyledPositionCard_Container..."> when the window size is middle.
<div class="StyledPositionCard_Thumnail..."> doesn't fit in the parent div <div class="StyledPositionCard_Container..."> when the window size is smaller than middle.

I commented out width: "90%":
 Opportunities.js  >  <OpportunitiesContainer>  > 
return (
    <div
          key={Math.random()}
          style={{
          width: "90%",
          ...
         }}
    > 
    ...
)

→ Children <div> of <div class="StyledPositionCard_Container..."> fit in <div class="StyledPositionCard_Container..."> for all the window sizes but the container size of the position card became not consistent.

**Comment by rinagobo** [comment]
From what I inspect using developer tool, deleting " width="100%" " from first <Box> component in <Actions> in PositionCard.tsx helped to move the "APPLY" button at a proper position![Screenshot 2023-04-23 at 3.24.49 PM.png](https://images.zenhubusercontent.com/64207ad43bdbe192c736be9a/c685bc3f-5caa-40e0-a43d-2f037639b7c6)!

**Comment by rinagobo** [comment]
After investigating files, the only page (other than ".../users/me" page) where the PositionCard of global component is used was: ".../dev-recruiters" page. 

My change on the global component file didn't affect ".../dev-recruiters" page.
![Screenshot 2023-04-25 at 12.46.30 PM.png](https://images.zenhubusercontent.com/64207ad43bdbe192c736be9a/35bfd460-f021-4381-b092-90fb6a6a421b)

**Comment by rinagobo** [comment]
For CardContainer component styling, I think it's better to delete width: 100%; because this helps  contents of OpportunitiesContainer fit in the container well while window size is changing.
![Screenshot 2023-04-25 at 12.48.11 PM.png](https://images.zenhubusercontent.com/64207ad43bdbe192c736be9a/d1d6bbf2-4274-4e34-9e11-645f41cdfc00)![Screenshot 2023-04-25 at 12.54.01 PM.png](https://images.zenhubusercontent.com/64207ad43bdbe192c736be9a/e2c61875-90c0-46a7-8017-3fd965e328b6)

**Comment by judeamos** [comment]
Hey @ethanzlevin, moving this task to the iced box for now. Waiting for your input.

**Comment by KaitlynMallare** [comment]
No longer needed - deleting/closing as not planned
